# Generated by Django 5.2.4 on 2026-07-03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(upload_to=users.models.avatar_upload_to),
        ),
    ]
