# Generated by Django 5.2.4 on 2026-07-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_skill_name_alter_user_about_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('name',), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined', '-id'), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
