# Generated by Django 5.2.4 on 2026-07-03

from django.db import migrations, models
from django.db.models import Q


def fill_empty_phone(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(phone__isnull=True).update(phone="")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_skill_options_alter_user_options"),
    ]

    operations = [
        migrations.RunPython(fill_empty_phone, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=12,
                verbose_name="Phone",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=~Q(phone=""),
                fields=("phone",),
                name="unique_non_empty_user_phone",
            ),
        ),
    ]
