# Generated by Django 5.2.4 on 2026-07-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_created_at_alter_project_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
