name: teamfinder_ad

services:
  db:
    image: postgres:16
    env_file:
      - .env
    container_name: teamfinder_ad_db
    ports:
      - "5436:5432"
    volumes:
      - teamfinder_ad_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  teamfinder_ad_postgres_data:
